version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "example-dependency"
        versions: ["1.x", "2.x"]
    reviewers:
      - "your-github-username"
